-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL AND FOLLOWS STRICT RULES
-- In other words, I ain't writing a lua parser for this, so please be a good boi/girl/whatever
-- Guarded for hosts without quickshell configured (e.g. thinkpad): the
-- anti-flashbang shader path is written by quickshell when it runs. If the file
-- is absent, skip it instead of erroring. quickshell rewrites this whole file
-- once it's set up here, so the guard self-heals.
local _af_shader = "/home/dustin/.config/quickshell/ii/services/hyprlandAntiFlashbangShader/anti-flashbang-weak.glsl"
do
	local _f = io.open(_af_shader)
	if _f then
		_f:close()
		hl.config({decoration={screen_shader=_af_shader}})
	end
end
hl.config({debug={damage_tracking=1}})
