# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
source=env.conf

# Don't let background/activating windows steal focus from the floating terminal scratchpad.
# (Browsers fire activate requests constantly for new tabs/links/popups.)
misc {
    focus_on_activate = false
}

input {
    repeat_rate = 25
    repeat_delay = 200

    kb_options = fkeys:basic_13-24
}

device {
    name = razer-razer-deathadder-elite
    sensitivity = -2.5
}

device {
    name = nulea-m504-gaming-mouse-keyboard
    sensitivity = -2.4
}

device {
    name = synps/2-synaptics-touchpad
    sensitivity = 0.0
}

device {
    name = dabstractor-dactyl-manuform-(5x7-1)-mouse
    sensitivity = 0.4
}
