-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Put general config stuff here
-- Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
-- (custom/env.lua is already required by hyprland.lua before this file)

hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 3,
		border_size = 1,
		no_focus_fallback = true,
		-- stop movefocus at the screen edge instead of wrapping
	},
})

hl.config({
	decoration = {
		rounding = 8,
	},
})

-- Dwindle split: instead of a 50/50 split, the RIGHT window takes ~80% of the
-- screen (left ~20%). Geometry is LEFT = width/2 * ratio, so ratio = 0.4 makes
-- the left 20% and the right 80%. This is positional (split_bias stays 0), so it
-- applies whenever a window lands on the right -- including after swaps, which
-- only exchange which window occupies a node (the 80% geometry persists).
-- Note: this same ratio also affects top/bottom splits (bottom gets ~80%).
-- Tweak live with SUPER+; / SUPER+' (splitratio -0.1 / +0.1).
hl.config({
	dwindle = {
		default_split_ratio = 0.6,
	},
})

-- Snappy animations — fast durations, minimal easing

hl.config({
	animations = {
		enabled = true,
		-- fast-in, snappy-out
	},
})

-- Don't let background/activating windows steal focus from the floating terminal scratchpad.

-- (Browsers fire activate requests constantly for new tabs/links/popups.)

hl.config({
	misc = {
		focus_on_activate = false,
	},
})

hl.config({
	input = {
		repeat_rate = 25,
		repeat_delay = 200,
		kb_options = "fkeys:basic_13-24",
	},
})

hl.device({
	name = "nulea-m504-gaming-mouse-keyboard",
	sensitivity = -1,
})

hl.device({
	name = "synps/2-synaptics-touchpad",
	sensitivity = 0.0,
})

hl.device({
	name = "dabstractor-dactyl-manuform-(5x7-1)-mouse",
	sensitivity = 0.4,
})

hl.config({
	binds = {
		scroll_event_delay = 0,
	},
})
