-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Put general config stuff here
-- Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
-- (custom/env.lua is already required by hyprland.lua before this file)

hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 3,
		border_size = 1,
		no_focus_fallback = true,
		-- stop movefocus at the screen edge instead of wrapping
	},
})

hl.config({
	decoration = {
		rounding = 8,
	},
})

-- Snappy animations — fast durations, minimal easing

hl.config({
	animations = {
		enabled = true,
		-- fast-in, snappy-out
	},
})

-- Don't let background/activating windows steal focus from the floating terminal scratchpad.

-- (Browsers fire activate requests constantly for new tabs/links/popups.)

hl.config({
	misc = {
		focus_on_activate = false,
	},
})

hl.config({
	input = {
		repeat_rate = 25,
		repeat_delay = 200,
		kb_options = "fkeys:basic_13-24",
	},
})

hl.device({
	name = "nulea-m504-gaming-mouse-keyboard",
	sensitivity = -1,
})

hl.device({
	name = "synps/2-synaptics-touchpad",
	sensitivity = 0.0,
})

hl.device({
	name = "dabstractor-dactyl-manuform-(5x7-1)-mouse",
	sensitivity = 0.4,
})

hl.config({
	binds = {
		scroll_event_delay = 0,
	},
})
