
# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrulev2 = move -100, title:^(jitsi\.mulletware\.io is sharing your screen.)$

# open floating popup windows a default size
windowrulev2 = float, title:^(Untitled - Google Chrome)$
windowrulev2 = size 1000px 600px, title:^(Untitled - Google Chrome)$

windowrulev2 = tile, title:^DevTools
windowrulev2 = maxsize 500 100%, title:^DevTools
# windowrulev2 = pseudo, title:^DevTools
windowrulev2 = noborder, title:^DevTools

windowrulev2 = move 100%-400px 100%-710px, title:^(Calculator)$
windowrulev2 = size 400px 600px, title:^(Calculator)$

windowrulev2 = float, title:^ClickUp$
windowrulev2 = size 49% 98%, title:^ClickUp$
windowrulev2 = move 0.4% 1%, title:^ClickUp$

windowrulev2 = float, title:^Mattermost$
windowrulev2 = size 80%, title:^Mattermost$
windowrulev2 = center, title:^Mattermost$

windowrulev2 = float, initialTitle:^Jitsi Meet
windowrulev2 = size 100%, initialTitle:^Jitsi Meet
windowrulev2 = center, initialTitle:^Jitsi Meet

windowrulev2 = float, initialTitle:^Zoho Mail$
windowrulev2 = size 60% 80%, initialTitle:^Zoho Mail$
windowrulev2 = center, initialTitle:^Zoho Mail

windowrulev2 = float, initialTitle:^Claude
windowrulev2 = size 80% 99.5%, initialTitle:^Claude
windowrulev2 = move 0% -1.2%, initialTitle:^Claude

windowrulev2 = float, initialTitle:^Google AI Studio
windowrulev2 = size 80% 99.5%, initialTitle:^Google AI Studio
windowrulev2 = move 0% -1.2%, initialTitle:^Google AI Studio

windowrulev2 = float, initialTitle:^Docmost
windowrulev2 = size 80% 99.5%, initialTitle:^Docmost
windowrulev2 = move 0% -1.2%, initialTitle:^Docmost

windowrulev2 = float, initialTitle:^YouTube Music
windowrulev2 = size 60% 80%, initialTitle:^YouTube Music
windowrulev2 = center, initialTitle:^YouTube Music

windowrulev2 = float, title:ytermusic
windowrulev2 = size 32% 20%, title:ytermusic
windowrulev2 = move 32% 74%, title:ytermusic

windowrulev2 = float, initialClass:^ClickUp$
windowrulev2 = size 49% 98%, initialClass:^ClickUp$
windowrulev2 = move 0.4% 1%, initialClass:^ClickUp$

windowrulev2 = fullscreen, initialClass:^steam_app.

windowrulev2 = fullscreen, initialClass:^.exe$

windowrulev2 = fullscreen, initialClass:^steam.*app
windowrulev2 = immediate, initialClass:^steam.*app

windowrulev2 = float, initialClass:.*nngceckbapebfimnlniiiahkandclblb.*
windowrulev2 = size 200 400, initialTitle:Bitwarden
