unbind=Super, Super_L
unbind=Super, Super_R
unbind=Super, Super_L
unbind=Super, Super_R
unbind=Super, catchall
unbind=Ctrl, Super_L
unbind=Ctrl, Super_R
unbind=Super, mouse:
unbind=Super, mouse:273
unbind=Super, mouse:274
unbind=Super, mouse:275
unbind=Super, mouse:276
unbind=Super, mouse:277
unbind=Super, mouse_up
unbind=Super, mouse_down
unbind=Super_L
unbind=Super_R
unbind=Super, V
unbind=Super, Period
unbind=Super, Tab
unbind=Super, A
unbind=Super+Alt, A
unbind=Super, B
unbind=Super, O
unbind=Super, N
unbind=Super, Slash
unbind=Super, K
unbind=Super, M
unbind=Super, G
unbind=Ctrl+Alt, Delete
unbind=Super, J
unbind=Shift+Super+Alt, Slash# Switch workspacs
unbind=Super, Minus
unbind=Super, Equal
unbind=Super, Minus
unbind=Super, Equal
unbind=Super, code:82
unbind=Super, code:86
unbind=Super, code:82
unbind=Super, code:86
unbind=Super+Alt, A
unbind=Super, Super_L
unbind=Super, Super_R
unbind=Super, Super_L
unbind=Super, Super_R
unbind=Super, catchall
unbind=Ctrl, Super_L
unbind=Ctrl, Super_R
unbind=Super, mouse:272
unbind=Super, mouse:273
unbind=Super, mouse:274
unbind=Super, mouse:275
unbind=Super, mouse:276
unbind=Super, mouse:277
unbind=Super, mouse_up
unbind=Super, mouse_down
unbind=Super+Shift, mouse_down
unbind=Super+Shift, mouse_up
unbind=Super+Alt, mouse_down
unbind=Super+Alt, mouse_up
unbind=Super+Alt, Page_Down
unbind=Super+Alt, Page_Up
unbind=Super+Shift, Page_Down
unbind=Super+Shift, Page_Up
unbind=Ctrl+Super+Shift, Right
unbind=Ctrl+Super+Shift, Left
unbind=Ctrl+Super, Right
unbind=Ctrl+Super, Left
unbind=Ctrl+Super+Alt, Right
unbind=Ctrl+Super+Alt, Left
unbind=Super, Page_Down
unbind=Super, Page_Up
unbind=Ctrl+Super, Page_Down
unbind=Ctrl+Super, Page_Up
unbind=Super, mouse_up
unbind=Super, mouse_down
unbind=Ctrl+Super, mouse_up
unbind=Ctrl+Super, mouse_down
unbind=Super, mouse:275
unbind=Ctrl+Super, BracketLeft
unbind=Ctrl+Super, BracketRight
unbind=Ctrl+Super, Up
unbind=Ctrl+Super, Down
unbind=Super+Alt, W
unbind=Super, V
unbind=Super, Period
unbind=Super+Shift, A
unbind=Super+Shift, X
unbind=Super+Shift, T
unbind=Super+Shift, C
unbind=Super+Shift, R
unbind=Super+Alt, R
unbind=Ctrl+Alt, R
unbind=Super+Shift+Alt, R
unbind=Super+Shift+Alt, mouse:273
unbind=Super, L
unbind=Super+Shift, L
unbind=Super, Return
unbind=Ctrl+Alt, T
unbind=Super, E
unbind=Super, W
unbind=Super, C
unbind=Ctrl+Super+Shift+Alt, W
unbind=Super, X
unbind=Ctrl+Super, V
unbind=Super, I
unbind=Ctrl+Shift, Escape
unbind=Super, P
