-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Remove the ALT+F4 "Wrong close keybind" reminder notification (defined in
-- hyprland/keybinds.lua). With no bind at all, the unbound keypress falls
-- through to the focused surface, so Alt+F4 still reaches Windows VMs running
-- under looking-glass — it just no longer fires the nag notification.
hl.unbind("ALT + F4")

-- hl.unbind("SUPER + SUPER_L")

-- hl.unbind("SUPER + SUPER_R")

-- hl.unbind("SUPER + SUPER_L")

-- hl.unbind("SUPER + SUPER_R")

-- hl.unbind("SUPER + catchall")  (no catchall bind defined in lua)

-- hl.unbind("CTRL + SUPER_L")

-- hl.unbind("CTRL + SUPER_R")

-- hl.unbind("SUPER + mouse:")  (no wildcard mouse: in lua; individual buttons unbound below)

-- hl.unbind("SUPER + mouse:273")

-- hl.unbind("SUPER + mouse:274")

-- hl.unbind("SUPER + mouse:275")

-- hl.unbind("SUPER + mouse:276")

-- hl.unbind("SUPER + mouse:277")

-- hl.unbind("SUPER + mouse_up")

-- hl.unbind("SUPER + mouse_down")

-- hl.unbind("SUPER_L")

-- hl.unbind("SUPER_R")

-- hl.unbind("SUPER + V")

-- hl.unbind("SUPER + Period")

-- hl.unbind("SUPER + Tab")

hl.unbind("SUPER + A")

hl.unbind("SUPER+ALT + A")

hl.unbind("SUPER+ALT + D")
hl.unbind("CTRL+SUPER+ALT + D")

hl.unbind("SUPER + B")

-- hl.unbind("SUPER + O")

-- hl.unbind("SUPER + N")

-- hl.unbind("SUPER + Slash")

hl.unbind("SUPER + K")

hl.unbind("SUPER + M")

hl.unbind("SUPER + G")

-- hl.unbind("CTRL+ALT + Delete")

hl.unbind("SUPER + J")

-- hl.unbind("SHIFT+SUPER+ALT + Slash")

-- Switch workspacs

hl.unbind("SUPER + Minus")

hl.unbind("SUPER + Equal")

hl.unbind("SUPER + Minus")

hl.unbind("SUPER + Equal")

hl.unbind("SUPER + code:82")

hl.unbind("SUPER + code:86")

hl.unbind("SUPER + code:82")

hl.unbind("SUPER + code:86")

hl.unbind("SUPER+ALT + A")

hl.unbind("SUPER + SUPER_L")

hl.unbind("SUPER + SUPER_R")

hl.unbind("SUPER + SUPER_L")

hl.unbind("SUPER + SUPER_R")

-- hl.unbind("SUPER + catchall")  (no catchall bind defined in lua)

hl.unbind("CTRL + SUPER_L")

hl.unbind("CTRL + SUPER_R")

hl.unbind("SUPER + mouse:272")

hl.unbind("SUPER + mouse:273")

hl.unbind("SUPER + mouse:274")

hl.unbind("SUPER + mouse:275")

hl.unbind("SUPER + mouse:276")

hl.unbind("SUPER + mouse:277")

hl.unbind("SUPER + mouse_up")

hl.unbind("SUPER + mouse_down")

hl.unbind("SUPER+SHIFT + mouse_down")

hl.unbind("SUPER+SHIFT + mouse_up")

hl.unbind("SUPER+ALT + mouse_down")

hl.unbind("SUPER+ALT + mouse_up")

hl.unbind("SUPER+ALT + Page_Down")

hl.unbind("SUPER+ALT + Page_Up")

hl.unbind("SUPER+SHIFT + Page_Down")

hl.unbind("SUPER+SHIFT + Page_Up")

hl.unbind("CTRL+SUPER+SHIFT + Right")

hl.unbind("CTRL+SUPER+SHIFT + Left")

hl.unbind("CTRL+SUPER + Right")

hl.unbind("CTRL+SUPER + Left")

hl.unbind("CTRL+SUPER+ALT + Right")

hl.unbind("CTRL+SUPER+ALT + Left")

hl.unbind("SUPER + Page_Down")

hl.unbind("SUPER + Page_Up")

hl.unbind("CTRL+SUPER + Page_Down")

hl.unbind("CTRL+SUPER + Page_Up")

hl.unbind("SUPER + mouse_up")

hl.unbind("SUPER + mouse_down")

hl.unbind("CTRL+SUPER + mouse_up")

hl.unbind("CTRL+SUPER + mouse_down")

hl.unbind("SUPER + mouse:275")

hl.unbind("CTRL+SUPER + BracketLeft")

hl.unbind("CTRL+SUPER + BracketRight")

hl.unbind("CTRL+SUPER + Up")

hl.unbind("CTRL+SUPER + Down")

hl.unbind("SUPER+ALT + W")

hl.unbind("SUPER + V")

hl.unbind("SUPER + Period")

hl.unbind("SUPER+SHIFT + A")

hl.unbind("SUPER+SHIFT+ALT + mouse:273")

hl.unbind("SUPER + L")

hl.unbind("SUPER+SHIFT + L")

hl.unbind("SUPER + Return")

hl.unbind("CTRL+ALT + T")

hl.unbind("SUPER + E")

hl.unbind("SUPER + W")

hl.unbind("SUPER + C")

hl.unbind("CTRL+SUPER+SHIFT+ALT + W")

hl.unbind("SUPER + X")

hl.unbind("CTRL+SUPER + V")

hl.unbind("SUPER + I")

hl.unbind("CTRL+SHIFT + Escape")

hl.unbind("SUPER + P")

hl.unbind("SUPER + Semicolon")

-- splitratio -> freed for hyprscratch obsidian vault
